# Generated by Django 4.2.7 on 2023-12-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kategoria', models.CharField(choices=[('komputer', 'komputer'), ('laptop', 'laptop'), ('tablet', 'tablet'), ('smartfon', 'martfon')], max_length=20)),
                ('cena', models.CharField(max_length=20)),
                ('producent', models.CharField(max_length=50)),
                ('kolor', models.CharField(max_length=35)),
                ('dostepnosc', models.IntegerField()),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=35, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('haslo', models.CharField(max_length=20)),
                ('powtorz_haslo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zalogowany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=35)),
                ('haslo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('adres_dostawy', models.CharField(max_length=70)),
                ('status', models.CharField(choices=[('Nowe', 'Nowe'), ('W trakcie realizacji', 'W trakcie realizacji'), ('Zrealizowane', 'Zrealizowane')], default='Nowe', max_length=50)),
                ('produkty', models.ManyToManyField(to='aplikacja.produkt')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.uzytkownik')),
            ],
        ),
    ]
