# Generated by Django 4.2.7 on 2023-12-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='nazwa',
            field=models.CharField(default='Zamowienie', max_length=50),
        ),
    ]
