# Generated by Django 4.2.7 on 2023-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0003_delete_zalogowany_remove_uzytkownik_powtorz_haslo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='haslo',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='imie',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='nazwisko',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='telefon',
            field=models.IntegerField(),
        ),
    ]
