# Generated by Django 4.2.7 on 2023-12-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0004_alter_uzytkownik_email_alter_uzytkownik_haslo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='nazwa',
            field=models.CharField(default='Zamowienie', max_length=35),
        ),
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='Koszyk', max_length=35)),
                ('produkty', models.ManyToManyField(to='aplikacja.produkt')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.uzytkownik')),
            ],
        ),
    ]
